compute_environment: LOCAL_MACHINE 
debug: false
distributed_type: "NO"
downcast_bf16: "no" # Whether to downcast bf16 to fp16. Useful for older GPUs that do not support bf16.
machine_rank: 0 # Rank of the machine in a distributed setup. For single machine, set to 0.
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false # Use GPU, not CPU-only
